namespace TelegramGasBot.Enums
{
    public enum UserCommandEnum
    {
        Unknown,
        BeginChat,
        StartAndRegisterUserInDb,
        SelectPersonalAccountsTabNoPersonalAccountAdded,
        ReturnToMenuTabNoPersonalAccountAdded,
        SelectAddPersonalAccountTabNoPersonalAccountAdded,
        InvalidPersonalAccountFormatNoPersonalAccountAdded,
        SelectReadindsTab,
        SelectPaymentsTab,
        SelectPersonalAccountsTab,
        ReturnToMenuTab,
        SelectDeletePersonalAccountTab,
        SelectAddPersonalAccountTab,
        InvalidPersonalAccountFormat,
        DeletePersonalAccountTab,
        SelectSendReadingsTab,
        SendReadingsTab,
        InvalidReadingsFormatTab,
        ConfirmPersonalAccountTab,
        ConfirmPersonalAccountTabNoPersonalAccountAdded,
        SavePersonalAccount,
        SavePersonalAccountNoPersonalAccountAdded,
        InvalidMeterNumberTabNoPersonalAccountAdded,
        InvalidMeterNumberTab,
    }
}
